### ISSUE TITLE
Only svg files in data downloaded

### ISSUE THREAD

**Issue by doralune** [floorplancad/floorplancad.github.io#1]
I have tried download data (train.tar, val.tar, test.tar) from https://floorplancad.github.io/ , but there are only svg files after decompressing. Is this correct ?

**Comment by aboudev** [comment]
Hi, we have updated the data, please checkout the website again.

**Comment by ogencoglu** [comment]
What is the relationship between image patches? Are they tiled versions of a larger image? Are file names some sort of coordinates? Is there overlap?
